### ISSUE TITLE
Enhancement: Transmit progress indicator

### ISSUE THREAD

**Issue by wb2osz** [maqifrnswa/PCSI#11]
Suggested enhancement:

Display the expected total transmit time for the image and some sort of progress indicator,

**Comment by maqifrnswa** [comment]
Good idea. To test it out, see the new continuously built windows and MacOS versions in [the readme file](README.md). You'll notice that you can send more than 100% of the image. That corresponds to the transmission starting over. You could sit on a channel as an image "fountain," sending the same image over and over. That will allow more people to eventually tune in and also gives redundancy in case someone missed some segment of the transmission. That said, the receiver does not need to receive 100% of the image, so the transmitter can stop whenever they feel it is appropriate. We'll eventually integrate a simulator in to it so the sender can estimate what the image would look like based on the number of packets received.
